"""Create saved_routes table

Revision ID: be45eb4da5f1
Revises: 70f407661583
Create Date: 2025-11-01 22:36:28.221550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be45eb4da5f1'
down_revision: Union[str, Sequence[str], None] = '70f407661583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_routes',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique route identifier'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owner of this saved route'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name for this saved route'),
    sa.Column('origin', sa.String(length=255), nullable=False, comment='Origin stop or location'),
    sa.Column('destination', sa.String(length=255), nullable=False, comment='Destination stop or location'),
    sa.Column('route_types', sa.String(length=100), nullable=True, comment='Preferred route types (comma-separated: subway,bus)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the route'),
    sa.Column('is_favorite', sa.Boolean(), nullable=False, comment='Whether this is a favorite route'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the route is active/enabled'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the route was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the route was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_routes_id'), 'saved_routes', ['id'], unique=False)
    op.create_index(op.f('ix_saved_routes_user_id'), 'saved_routes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_routes_user_id'), table_name='saved_routes')
    op.drop_index(op.f('ix_saved_routes_id'), table_name='saved_routes')
    op.drop_table('saved_routes')
    # ### end Alembic commands ###
